### ISSUE TITLE
Comments are not appearing

### ISSUE THREAD

**Issue by syedfkabir** [curveball/browser#141]
## Task 

Comments aren't appearing inside of objects and arrays in the HAL browser.
(see example): the comment for `summary` would appear, but for `title` it would not
They are appearing for 'primary' properties, but not for 'secondary'. 

## Example

```
export interface randomObject {

  _links?: { };

  data: someCollection[];

  /**
   * The summary of the video.
   */
  summary: {
  /**
   * The title of the video.
   */
  title: number;
  }
}
```

**Comment by evert** [comment]
Interesting screenshot choice, but bug makes sense!
